### Project 1: BRFSS Mental Health Analysis
#### Notebook 01: Data Cleaning
**Author:** Amanda Shero  
**Date:** March 2026  
**Description:** Loads the 2023 BRFSS dataset, subsets to project variables, 
handles special codes and missing values, and outputs a clean dataframe ready for EDA.

In [1]:
import pandas as pd
import numpy as np

# Load raw data
# Note: pd.read_sas used instead of pyreadstat due to XPT character encoding issue
df_raw = pd.read_sas('LLCP2023.XPT', format='xport', encoding='latin-1')

print(f"Raw data shape: {df_raw.shape}")

Raw data shape: (433323, 350)

In [2]:
df_raw.head(10)

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4,_RFSEAT2,_RFSEAT3,_DRNKDRV
0,1.0,1.0,03012023,03,01,2023,1100.0,2023000001,2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,1.0,1.0,9.0
1,1.0,1.0,01062023,01,06,2023,1100.0,2023000002,2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
2,1.0,1.0,03082023,03,08,2023,1100.0,2023000003,2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
3,1.0,1.0,03062023,03,06,2023,1100.0,2023000004,2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,9.0
4,1.0,1.0,01062023,01,06,2023,1100.0,2023000005,2.023000e+09,1.0,...,7.000000e+00,1.0,4.700000e+01,1.0,2.0,1.0,2.0,1.0,1.0,2.0
5,1.0,1.0,01092023,01,09,2023,1100.0,2023000006,2.023000e+09,1.0,...,1.700000e+01,1.0,2.330000e+02,1.0,NaN,NaN,1.0,1.0,1.0,2.0
6,1.0,1.0,03212023,03,21,2023,1100.0,2023000007,2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,9.0
7,1.0,1.0,01062023,01,06,2023,1100.0,2023000008,2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
8,1.0,1.0,03152023,03,15,2023,1100.0,2023000009,2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
9,1.0,1.0,01082023,01,08,2023,1100.0,2023000010,2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0

In [ ]:
df_raw[['_STATE', 'FMONTH', 'IYEAR', '_DRNKWK2' ]]

        _STATE  FMONTH IYEAR      _DRNKWK2
0          1.0     1.0  2023  5.397605e-79
1          1.0     1.0  2023  5.397605e-79
2          1.0     1.0  2023  5.397605e-79
3          1.0     1.0  2023  5.397605e-79
4          1.0     1.0  2023  4.700000e+01
...        ...     ...   ...           ...
433318    78.0    12.0  2023  1.500000e+03
433319    78.0    12.0  2024  5.397605e-79
433320    78.0    12.0  2023  4.700000e+01
433321    78.0    12.0  2023  5.397605e-79
433322    78.0    12.0  2023  9.330000e+02

[433323 rows x 4 columns]

In [ ]:
# Check the demographics variable exist
demo_vars = ['_AGEG5YR', 'SEXVAR', '_RACE1', 'EDUCA', 'INCOME3', 'MARITAL', 'EMPLOY1', '_URBSTAT']

for var in demo_vars:
    print(var, var in df_raw.columns)

_AGEG5YR True
SEXVAR True
_RACE1 False
EDUCA True
INCOME3 True
MARITAL True
EMPLOY1 True
_URBSTAT True

In [7]:
[col for col in df_raw.columns if 'RACE' in col]

['_IMPRACE', '_CRACE1', '_MRACE1', '_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV']

In [9]:
df_raw[['_IMPRACE', '_CRACE1', '_MRACE1', '_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV']]

        _IMPRACE  _CRACE1  _MRACE1  _RACE  _RACEG21  _RACEGR3  _RACEPRV
0            1.0      NaN      1.0    1.0       1.0       1.0       1.0
1            1.0      NaN      1.0    1.0       1.0       1.0       1.0
2            2.0      NaN      2.0    2.0       2.0       2.0       2.0
3            1.0      NaN      1.0    1.0       1.0       1.0       1.0
4            1.0      NaN      1.0    1.0       1.0       1.0       1.0
...          ...      ...      ...    ...       ...       ...       ...
433318       2.0      NaN      2.0    2.0       2.0       2.0       2.0
433319       2.0      NaN      2.0    2.0       2.0       2.0       2.0
433320       5.0      NaN      2.0    8.0       2.0       5.0       8.0
433321       2.0      NaN      2.0    2.0       2.0       2.0       2.0
433322       2.0      NaN      2.0    2.0       2.0       2.0       2.0

[433323 rows x 7 columns]

In [11]:
# Check the health status variables exist
health_vars = ['GENHLTH', 'PHYSHLTH', 'ADDEPEV3', 'DIABETE4', 'CVDINFR4', 'ASTHMA3', 'HAVARTH4', 'CHCCOPD3']

for var in health_vars:
    print(var, var in df_raw.columns)

GENHLTH True
PHYSHLTH True
ADDEPEV3 True
DIABETE4 True
CVDINFR4 True
ASTHMA3 True
HAVARTH4 True
CHCCOPD3 True

In [12]:
# Check the behavioral variables exist
behavior_vars = ['SLEPTIM1', 'EXERANY2', 'SMOKDAY2', 'AVEDRNK3', 'DRNK3GE5']

for var in behavior_vars:
    print(var, var in df_raw.columns)

SLEPTIM1 False
EXERANY2 True
SMOKDAY2 True
AVEDRNK3 True
DRNK3GE5 True

SLEPTIM1 not present in the February 2025 modified release of the 2023 BRFSS file — excluded from analysis.

In [18]:
[col for col in df_raw.columns if 'TIM' in col]

['SAFETIME', 'PSATIME1']

In [19]:
access_vars = ['HLTHPLN2', 'MEDCOST1', 'PERSDOC3']

for var in access_vars:
    print(var, var in df_raw.columns)

HLTHPLN2 False
MEDCOST1 True
PERSDOC3 True

In [20]:
'_HLTHPL1' in df_raw.columns

True

In [26]:
df_clean = df_raw[['_AGEG5YR', 'SEXVAR', '_RACE', 'EDUCA', 'INCOME3', 'MARITAL', 'EMPLOY1', '_URBSTAT', 
        'GENHLTH', 'PHYSHLTH', 'ADDEPEV3', 'DIABETE4', 'CVDINFR4', 'ASTHMA3', 'HAVARTH4', 'CHCCOPD3', 
        'EXERANY2', 'SMOKDAY2', 'AVEDRNK3', 'DRNK3GE5',
        '_HLTHPL1', 'MEDCOST1', 'PERSDOC3', 
        'MENTHLTH', '_MENT14D']]

In [27]:
df_clean

,_AGEG5YR,SEXVAR,_RACE,EDUCA,INCOME3,MARITAL,EMPLOY1,_URBSTAT,GENHLTH,PHYSHLTH,...,CHCCOPD3,EXERANY2,SMOKDAY2,AVEDRNK3,DRNK3GE5,_HLTHPL1,MEDCOST1,PERSDOC3,MENTHLTH,_MENT14D
0,13.0,2.0,1.0,5.0,99.0,1.0,7.0,1.0,2.0,88.0,...,2.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0,88.0,1.0
1,13.0,2.0,1.0,5.0,99.0,2.0,7.0,1.0,2.0,88.0,...,2.0,1.0,NaN,NaN,NaN,1.0,2.0,1.0,88.0,1.0
2,13.0,2.0,2.0,4.0,2.0,3.0,7.0,1.0,4.0,6.0,...,2.0,1.0,3.0,NaN,NaN,1.0,1.0,1.0,2.0,2.0
3,12.0,2.0,1.0,5.0,99.0,1.0,7.0,1.0,2.0,2.0,...,2.0,1.0,NaN,NaN,NaN,1.0,2.0,1.0,88.0,1.0
4,12.0,2.0,1.0,5.0,7.0,3.0,8.0,1.0,4.0,88.0,...,2.0,1.0,NaN,1.0,88.0,1.0,2.0,1.0,88.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433318,10.0,1.0,2.0,5.0,5.0,2.0,1.0,NaN,3.0,12.0,...,2.0,1.0,NaN,3.0,2.0,9.0,2.0,1.0,30.0,3.0
433319,3.0,2.0,2.0,6.0,6.0,5.0,1.0,NaN,2.0,88.0,...,2.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0,88.0,1.0
433320,7.0,2.0,8.0,6.0,10.0,1.0,1.0,NaN,2.0,10.0,...,2.0,1.0,NaN,2.0,88.0,1.0,2.0,2.0,88.0,1.0
433321,10.0,2.0,2.0,6.0,3.0,5.0,4.0,NaN,3.0,88.0,...,2.0,1.0,NaN,NaN,NaN,1.0,2.0,1.0,88.0,1.0
433322,6.0,1.0,2.0,2.0,2.0,5.0,2.0,NaN,5.0,2.0,...,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,88.0,1.0

In [28]:
df_clean = df_clean.copy()

In [29]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Data columns (total 25 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   _AGEG5YR  433323 non-null  float64
 1   SEXVAR    433323 non-null  float64
 2   _RACE     433237 non-null  float64
 3   EDUCA     433314 non-null  float64
 4   INCOME3   425248 non-null  float64
 5   MARITAL   433316 non-null  float64
 6   EMPLOY1   430355 non-null  float64
 7   _URBSTAT  425000 non-null  float64
 8   GENHLTH   433319 non-null  float64
 9   PHYSHLTH  433320 non-null  float64
 10  ADDEPEV3  433320 non-null  float64
 11  DIABETE4  433318 non-null  float64
 12  CVDINFR4  433320 non-null  float64
 13  ASTHMA3   433320 non-null  float64
 14  HAVARTH4  433319 non-null  float64
 15  CHCCOPD3  433320 non-null  float64
 16  EXERANY2  433321 non-null  float64
 17  SMOKDAY2  158639 non-null  float64
 18  AVEDRNK3  212126 non-null  float64
 19  DRNK3GE5  211689 non-null  float64
 20  _HLTHPL1  433323 non-null  float64
 21  MEDCOST1  433321 non-null  float64
 22  PERSDOC3  433320 non-null  float64
 23  MENTHLTH  433320 non-null  float64
 24  _MENT14D  433323 non-null  float64
dtypes: float64(25)
memory usage: 82.6 MB

These don't match the 7/9 pattern:
* _AGEG5YR -- 7 and 9 are valid options (Age 50 to 54; Age 60 to 64 respectively); 14 is Don't know/Refused/Missing
* SEXVAR -- only has two options: 1/Male, 2/Female
* _RACE -- 7 is a valid option (Multiracial, non-Hispanic), 9 is Don't know/Not sure/Refused
* EMPLOY1 -- 7 is a valid option (Retired), 9 is Refused




These match the 7/9 pattern:
* EDUCA -- doesn't have a 7 but does have a 9 = Refused
* INCOME3 -- uses 77 and 99
* MARITAL -- doesn't have a 7 but does have 9 = Refused
* _URBSTAT -- just has two options (1, 2) and BLANK
* GENHLTH
* PHYSHLTH -- uses 77 and 99
* ADDEPEV3
* DIABETE4
* CVDINFR4
* ASTHMA3
* HAVARTH4
* CHCCOPD3
* EXERANY2
* SMOKDAY2
* AVEDRNK3 -- uses 77 and 99
* DRNK3GE5 -- uses 77 and 99
* _HLTHPL1 -- doesn't have a 7 but does have a 9 = Refused
* MEDCOST1
* PERSDOC3

In [ ]:
# Replacing 88/None with 0; 77/Don't know or Not sure with NaN, and 99/Refused with NaN
df_clean['MENTHLTH'] = df_clean['MENTHLTH'].replace({88:0, 77:np.nan, 99:np.nan})

In [31]:
df_clean['MENTHLTH'].value_counts(dropna=False).head(10)

MENTHLTH
0.0     257026
30.0     25573
2.0      23878
5.0      19959
10.0     15426
3.0      15394
1.0      14173
15.0     14152
20.0      9065
NaN       8108
Name: count, dtype: int64

In [32]:
df_clean['_MENT14D'].value_counts(dropna=False)

_MENT14D
1.0    257026
2.0    110120
3.0     58069
9.0      8108
Name: count, dtype: int64

In [33]:
df_clean['_MENT14D'] = df_clean['_MENT14D'].replace(9, np.nan)

In [34]:
df_clean['_MENT14D'].value_counts(dropna=False)

_MENT14D
1.0    257026
2.0    110120
3.0     58069
NaN      8108
Name: count, dtype: int64

In [ ]:
# Replacing 7 and 9 responses with NaN
vars_7_9 = ['EDUCA', 'MARITAL', '_URBSTAT', 'GENHLTH', 'ADDEPEV3', 'DIABETE4', 'CVDINFR4', 'ASTHMA3', 'HAVARTH4', 'CHCCOPD3', 'EXERANY2', 
            'SMOKDAY2', '_HLTHPL1', 'MEDCOST1', 'PERSDOC3']

for var in vars_7_9:
    df_clean[var] = df_clean[var].replace({7:np.nan, 9:np.nan})

In [ ]:
# Replacing 77 and 99 responses with NaN
vars_77_99 = ['INCOME3', 'PHYSHLTH', 'AVEDRNK3', 'DRNK3GE5']

for var in vars_77_99:
    df_clean[var] = df_clean[var].replace({77:np.nan, 99:np.nan})

In [37]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Data columns (total 25 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   _AGEG5YR  433323 non-null  float64
 1   SEXVAR    433323 non-null  float64
 2   _RACE     433237 non-null  float64
 3   EDUCA     430998 non-null  float64
 4   INCOME3   346700 non-null  float64
 5   MARITAL   429034 non-null  float64
 6   EMPLOY1   430355 non-null  float64
 7   _URBSTAT  425000 non-null  float64
 8   GENHLTH   432061 non-null  float64
 9   PHYSHLTH  422538 non-null  float64
 10  ADDEPEV3  430736 non-null  float64
 11  DIABETE4  432339 non-null  float64
 12  CVDINFR4  430755 non-null  float64
 13  ASTHMA3   431622 non-null  float64
 14  HAVARTH4  430763 non-null  float64
 15  CHCCOPD3  431257 non-null  float64
 16  EXERANY2  432072 non-null  float64
 17  SMOKDAY2  158280 non-null  float64
 18  AVEDRNK3  209735 non-null  float64
 19  DRNK3GE5  209148 non-null  float64
 20  _HLTHPL1  414649 non-null  float64
 21  MEDCOST1  431785 non-null  float64
 22  PERSDOC3  429089 non-null  float64
 23  MENTHLTH  425215 non-null  float64
 24  _MENT14D  425215 non-null  float64
dtypes: float64(25)
memory usage: 82.6 MB

In [38]:
# Replacing 14/Don't know/Refused/Missing with NaN for _AGEG5YR
df_clean['_AGEG5YR'] = df_clean['_AGEG5YR'].replace({14:np.nan})

# Replacing 9/Don't know/Not sure/Refused with NaN for _RACE
df_clean['_RACE'] = df_clean['_RACE'].replace({9:np.nan})

# Replacing 9/Refused with NaN for EMPLOY1
df_clean['EMPLOY1'] = df_clean['EMPLOY1'].replace({9:np.nan})

In [39]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Data columns (total 25 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   _AGEG5YR  425544 non-null  float64
 1   SEXVAR    433323 non-null  float64
 2   _RACE     423753 non-null  float64
 3   EDUCA     430998 non-null  float64
 4   INCOME3   346700 non-null  float64
 5   MARITAL   429034 non-null  float64
 6   EMPLOY1   425642 non-null  float64
 7   _URBSTAT  425000 non-null  float64
 8   GENHLTH   432061 non-null  float64
 9   PHYSHLTH  422538 non-null  float64
 10  ADDEPEV3  430736 non-null  float64
 11  DIABETE4  432339 non-null  float64
 12  CVDINFR4  430755 non-null  float64
 13  ASTHMA3   431622 non-null  float64
 14  HAVARTH4  430763 non-null  float64
 15  CHCCOPD3  431257 non-null  float64
 16  EXERANY2  432072 non-null  float64
 17  SMOKDAY2  158280 non-null  float64
 18  AVEDRNK3  209735 non-null  float64
 19  DRNK3GE5  209148 non-null  float64
 20  _HLTHPL1  414649 non-null  float64
 21  MEDCOST1  431785 non-null  float64
 22  PERSDOC3  429089 non-null  float64
 23  MENTHLTH  425215 non-null  float64
 24  _MENT14D  425215 non-null  float64
dtypes: float64(25)
memory usage: 82.6 MB

In [40]:
df_clean.to_csv('df_clean.csv', index=False)

Cleaned 25 variables, recoded special codes to NaN, saved clean dataframe to CSV